### ISSUE TITLE
Module not visible.

### ISSUE THREAD

**Issue by kiborg** [pfortin-expertime/MageFix-Misc#1]
I dropped this module into app/code and ran magento module:status but I don't see it there. Why?

**Comment by legweilo** [comment]
Hi @kiborg,

you need to create a folder MageFix in app/code and then place the code in Misc folder:
> app/code/MageFix/Misc

I've also fixed an issue with the di.xml file, you should get the version 0.0.2

**Comment by kiborg** [comment]
ok it worked and fixed the issue. But why not to have it in right folders right away?
